version: "3.9"

services:
  minio_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minio_client
    restart: always
    ports:
      - "8024:8024"
    volumes:
      - .:/minio_client
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8024/graphql" ]
      interval: 30s
      timeout: 10s
      retries: 3