version: "3.9"

services:
  minio_client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8023
    container_name: minio_client
    restart: always
    ports:
      - "8023:8023"
    volumes:
      - .:/minio_client
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8023/graphql" ]
      interval: 30s
      timeout: 10s
      retries: 3