version: "3.9"

services:
  minio_client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minio_client
    command: uvicorn app.main:app --host 0.0.0.0 --port 8024
    restart: always
    ports:
      - "8024:8024"
    volumes:
      - .:/minio_client